faceswap/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'
urlpatterns = [
	url(r'^$', views.index,name="index"),
	url(r'^upload_source_image/$', views.upload_source_image,name="upload_source_image"),
	url(r'^upload_dest_image/$', views.upload_dest_image,name="upload_dest_image"),
	url(r'^blend/$', views.blend,name="blend"),
]

main/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Image(models.Model):
	im_type = models.CharField(max_length=250)
	im_field = models.FileField()

main/forms.py
from django import forms
from django.conf import settings

class ImageForm(forms.Form):
    image = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': False}))

main/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
import os
from .forms import ImageForm
from .models import Image
from django.core.files import File
from django.conf import settings


def index(request):
    source_image = None
    dest_image = None
    output_image = None
    for image in Image.objects.all():
        if image.im_type == 'source':
            source_image = image
        if image.im_type == 'dest':
            dest_image = image
        if image.im_type == 'output':
            output_image = image

    C = {
        'source_image' : source_image,
        'dest_image' : dest_image,
        'output_image' : output_image,
    }
    print(source_image.im_field.url)

    return render(request,'main/index.html',C)


def upload_source_image(request):
    
    form  = ImageForm(request.POST or None, request.FILES or None)
    
    if form.is_valid():
        for image in Image.objects.all():
            if image.im_type == 'source':
                image.delete()
        I = Image(im_type='source',im_field=request.FILES['image'])
        I.save()
        success_url = '../'
        return redirect(success_url)
        pass

    context = {
        'form' : form,
    }
    return render(request,'main/upload_image.html',context)


def upload_dest_image(request):
    
    form  = ImageForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        for image in Image.objects.all():
            if image.im_type == 'dest':
                image.delete()
        I = Image(im_type='dest',im_field=request.FILES['image'])
        I.save()
        success_url = '../'
        return redirect(success_url)
        pass

    context = {
        'form' : form,
    }
    return render(request,'main/upload_image.html',context)

def blend(request):
    FACESWAP_DIR = settings.FACESWAP_DIR
    M = settings.BASE_DIR
    source_image = None
    dest_image = None
    output_image = None
    for image in Image.objects.all():
        if image.im_type == 'source':
            source_image = image
        if image.im_type == 'dest':
            dest_image = image
    

    for image in Image.objects.all():
        if image.im_type == 'output':
            image.delete()
    cmd = "python " + FACESWAP_DIR + "/faceswap.py " + M + source_image.im_field.url + " " + M + dest_image.im_field.url
    print(cmd) 
    if settings.AUTHOR == 'nitish':
        os.system(cmd)
        lcml = "cp "+settings.BASE_DIR+'/output.jpg ' + settings.MEDIA_ROOT
        os.system(lcml)
    local_file = open('media/output.jpg','rb')
    djangofile = File(local_file)
    output_image = Image(im_type='output',im_field=djangofile)
    output_image.save()
    local_file.close()

    success_url = '../'
    return redirect(success_url)
    

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%} Core {% endblock %}</title>
    <!-- {% load staticfiles %} -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'garments/style.css' %}"/> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    {% block navigation %}
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">

                <!-- Header -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'main:index' %}"> FaceSwap TRI3D </a>
                </div>

                <div class="collapse navbar-collapse" id="topNavBar">
                    <ul class="nav navbar-nav navbar-right">
                        
                        <li>
                            <a href="{% url 'admin:index'%}">
                                <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>&nbsp; Admin Site
                            </a>
                        </li>
                        
                    </ul>
                </div>

                
            </div>
        </nav>

    {% endblock %}
    
    {% block body %}
    {% endblock %}
</body>

</html>

main/templates/main/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block body %}
Takes facial features of Destination Image and Blends it with Source Image
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">

<table>
	<thead>
		<tr>
			<th> Source </th>
			<th> Dest </th>
			<th> Output </th>

		</tr>
	</thead>

	<tbody>
		<tr>
			<td> <a type="button" class="btn btn-primary" href="{% url 'main:upload_source_image' %}">Upload Source</a> </td>
			<td> <a type="button" class="btn btn-primary" href="{% url 'main:upload_dest_image' %}">Upload Dest</a> </td>
			<td> <a type="button" class="btn btn-primary" href="{% url 'main:blend' %}"> Blend </a> </td>
		</tr>
		<tr>
			<td> <img src='{{source_image.im_field.url}}' style="max-height:100%; max-width:100%"> </img> </td>
			<td> <img src='{{dest_image.im_field.url}}' style="max-height:100%; max-width:100%"> </img> </td>
			<td> <img src='{{output_image.im_field.url}}' style="max-height:100%; max-width:100%"> </img> </td>
		</tr>

		
	</tbody>
</table>

</div>
</div>
</div>
</div>
</div>


{% endblock %}

main/templates/main/upload_image.html
<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="garment" value="{{ garment }}">
                        {% include 'main/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
</form>